{{- if .Values.image.automation.enabled -}}
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: {{ template "api.name" . }}
  namespace: {{ .Values.image.automation.namespace }}
spec:
  imageRepositoryRef:
    name: {{ template "api.name" . }}
  policy:
    semver:
      range: {{ .Values.image.automation.semver.expr }}
{{- end}}
