{{- if .Values.image.automation.enabled -}}
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: {{ .Release.Namespace }}-{{ template "api.name" . }}
  namespace: {{ .Values.image.automation.namespace }}
spec:
  image: "{{ .Values.image.repository }}"
  interval: {{ .Values.image.automation.interval }}
  {{- end}}
