---
replicaCount: 1

image:
  repository: repository/image
  tag: 1.0.0
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

deployment:
  containerPort: 8000
  antiaffinity:
    enabled: false

livenessProbe:
  path: "/healthz"
  port: http
  initialDelaySeconds: 5

readinessProbe:
  path: "/healthz"
  port: http
  initialDelaySeconds: 5

ports:
- name: http
  containerPort: 8000
  protocol: TCP

service:
  type: ClusterIP
  port: 80
  sslport: 443
  annotations: {}

servicePort: http

ingress:
  enabled: false
  class: kong
  annotations: {}
  hosts:
  - host: example1.local
    paths: ["/v2/api"]
  - host: example2.local
    paths: ["/v1/api"]
  rewrite: ""
  tls:
    enabled: false

ingressApicell:
  enabled: false
  class: kong-apicell
  annotations: {}
  hosts:
  - host: example1.local
    paths: ["/v2/api"]
  - host: example2.local
    paths: ["/v1/api"]
  rewrite: ""
  tls:
    enabled: false

prometheus:
  enabled: true

annotations: {}

labels: {}

resources:
  requests:
    cpu: 56m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 512Mi

hpa:
  enabled: true
  maxReplicas: 5
  cpu: 95
  memory: 95

env:
- name: SERVER_PORT
  value: "8000"

addEnv: {}

config: {}

configPath: /config/
configFilename: config.yaml

secrets: {}

certs: {}

certsMountPath: /app/secrets/
certsMountSubPath: {}

nodeSelector: {}

tolerations: []

affinity: {}
